### ISSUE TITLE
How to config to allow input empty string by just type `"` twice.

### ISSUE THREAD

**Issue by hackwaly** [Fuco1/smartparens#462] opened 2015-05-01 08:34 UTC
I'm sorry this is a idiot question. 
I've been confused that how to config to get this behavior:
type `""` -> `""|` not the default `""|""`

**Comment by Fuco1** [comment] 2015-05-01 09:42
This should be possible using the `:unless` specification, telling SP to not insert the pair if the point is inside an empty string.  It gets a bit more complicated with strings because the state flips when only the opening is inserted (which is when SP does the test). But it is possible...

So I would most likely need some better solution in the core.  For now your best option is to "untrain" yourself from hitting the key twice :/

**Comment by sooheon** [comment] 2015-06-24 14:22
@Fuco1, could you give an example snippet implementing this `:unless`?

**Comment by Fuco1** [comment] 2015-06-28 21:06
@sooheon The problem is that by the time sp tests the situation, your input buffer contains `""|"`, so you are in fact *outside* the string.  However, we can't test the state before the key is inserted because no event has been fired yet.  So you need to test something like "there's a quote behind the point, what happens if I remove it?".  I guess you get the idea.

In the basic case, testing if there are two " behind and one in front is what you want.

**Comment by Fuco1** [comment] 2015-08-13 14:59
We should add some default implementation for such a test as it seems to be rather common requirement.

**Comment by aldanor** [comment] 2016-02-25 19:35
Wondering if this is still something in the plans, maybe adding a global config option? Not being able to type empty quotes without having to `C-f` is a bit sad and different from most smart-quotes implementations in other text editors.

(there's also a few issues about this open in spacemacs)

Thanks!

**Comment by Wilfred** [comment] 2016-02-25 20:45
In principle I'd have expected `sp-skip-closing-pair` to handle this. We do the right thing for `)`, so `"` should be equivalent as far as I can see.

**Comment by aldanor** [comment] 2016-02-25 21:58
That would be neat to have. Should it be a separate option for quotes or should `sp-skip-closing-pair` affect both?

**Comment by Fuco1** [comment] 2016-05-21 12:13
Today I've found a bug that possibly caused this issue... it should've never happened in the first place.

If anyone cares to try the master, feel free to report back :)

**Comment by Fuco1** [comment] 2016-06-18 19:08
What OP wants is now default behaviour (and was the sensible thing all along).  Can you please try it out someone?

**Comment by sooheon** [comment] 2016-06-18 22:20
Can confirm that this behaviour works correctly, with both `sp-autoskip-closing-pair` `'always` and `'always-end`. However, now it seems to override the auto-pair mechanism for escaped quotation marks within strings. Previously, starting from: `"|"` where `|` is cursor, pressing `\"` would result in: `"\"|\""`. In other words, it would auto pair the escaped inner quotation. Now, it gives me `"\"|`, which leaves me with unbalanced pairs, not something you'd normally want.

**Comment by Fuco1** [comment] 2016-06-18 22:29
Ouch, that is indeed unfortunate.  I'll tackle it in the morning.  Thanks for pinging back!

**Comment by Fuco1** [comment] 2016-06-19 10:23
This should be fixed now as well

**Closed** 2016-07-04 19:45 UTC
Labels: bug, needs-verification, quotes
