### ISSUE TITLE
Issues when wrapping a region of OCaml code with parenthesese

### ISSUE THREAD

**Issue by tddsg** [Fuco1/smartparens#729] opened 2017-04-08 13:13 UTC
## Expected behavior

When marking the region `plus x y` (from left to right) in the below OCaml code, and press `(` to enclose it in parentheses:

```
let plus x y =
  x + y
```

the expected result should be:

```
let (plus x y) =
  x + y
```

## Actual behavior:

The actual result appears to be:

```
let (plus x (**) () =
  x + y
```

## Steps to reproduce the problem
- Write the following code in OCaml:

```
let plus x y =
  x + y
```

- Place the cursor before `plus` (the cursor is indicated by `|`)

```
let |plus x y =
  x + y
```

- And set the mark region until after `y` (the region is indicated inside the pair `'...'`, and the cursor is indicated by `|`)

```
let 'plus x y'| =
  x + y
```

- Now press `(` to enclose the marked region by parentheses, the result appears like below:

```
let (plus x (**) () =
  x + y
```

Here the string `(**) ()` appear as 1 character: if I place the cursor before the first `(`, and press the right arrow once, it will move over the last `)`

## Environment & version information

- `smartparens` version: 20170303.346 (suffix name of package installed by Spacemacs)
- Active major-mode: Tuareg
- Emacs version (`M-x emacs-version`): 25.1.1
- OS: Linux Mint 18.1

**Comment by Fuco1** [comment] 2017-04-08 16:00
I can't reproduce this on Emacs 24.5.  I still haven't switched over to 25.1 :/

Is there some background color on the `(**) ()`?  It might be a "tooltip" overlay SP creates to give you list of availble pairs.

Try to run

```elisp
(-each (overlays-in (point-min) (point-max))
  (lambda (o)
    (when (eq (overlay-get o 'type) 'wrap)
      (delete-overlay o))))
```

when you get that to see if it disappears.  Also try setting `sp-wrap-show-possible-pairs` to nil.  This will help me debug the case.

**Comment by tddsg** [comment] 2017-04-08 16:48
Hi,

- When running your script, the problem doesn't disappear.

```
(-each (overlays-in (point-min) (point-max))
  (lambda (o)
    (when (eq (overlay-get o 'type) 'wrap)
      (delete-overlay o))))
```

- But you are right, the `(**) ()` could be an overlay since if I kill the buffer and reopen it, that string disappears.

- When setting `sp-wrap-show-possible-pairs`, the overlay doesn't appear, but the result is not correct, as below:

```
let (plus x  = 
   x + y
```
- I also wrote an additional code in my emacs setting to enable smartparens handling comments in OCaml. Will it affect the way smartparens handle `(`?

```
(sp-with-modes '(tuareg-mode)
    (sp-local-pair "(*" "*)" :post-handlers '(sp-insert-pair)))
```

**Comment by Fuco1** [comment] 2017-04-09 11:31
I think the post-handler there is incorrect, it is not a permission but an (internal) function which inserts pairs.  I think that mightbe the problem.

**Comment by tddsg** [comment] 2017-04-09 12:34
Oh, it's my mistake when mimicking the smartparens-latex.

- However, even when I remove the post-handlers and use only the following code, the problem still occurs.

```
(sp-with-modes '(tuareg-mode)
     (sp-local-pair "(*" "*)" ))
```

- If I didn't declare the local pair like above, then the parentheses enclosing is OK.

- Could you double with only this configuration? This is the minimal environment that still causes the problem:

```
(sp-with-modes '(tuareg-mode)
     (sp-local-pair "(*" "*)" ))
```

**Comment by Fuco1** [comment] 2017-04-09 13:29
Yes, I can reproduce it now.  This is definitely a bug :)  Thanks for the investigation, I'll look into it.

**Comment by tddsg** [comment] 2017-04-09 13:33
Thank you too! :-)

**Comment by tddsg** [comment] 2017-04-10 21:21
I just want to follow up with this issue is that starting a comment in a big size OCaml file can be slow in the default setting, i.e., the pair `(* *)` isn't set as a local pair in smartparens.

In particular, if I type `(` first, then smartparens automatically makes it become `()`.

If I continue to type `*` in the middle of `()` to obtain `(*|)`, where `|` is the cursor position,
then Emacs becomes very slow. I guess it tries to re-parse the file and is problematic somewhere.

**Comment by Fuco1** [comment] 2017-04-11 08:33
It would depend on how the comment syntax is implemented in tuareg.  But better open a separate issue for this.

**Comment by tddsg** [comment] 2017-04-12 00:10
Thanks! I opened another issue here: https://github.com/Fuco1/smartparens/issues/730

**Comment by tddsg** [comment] 2017-04-28 01:43
Could I ask how is the status of this bug? Is there any case that I can help?

**Comment by Fuco1** [comment] 2017-04-28 09:13
@tddsg I fixed a similar issue in 1.10 in latex mode but I'm not sure if it also fixed this (haven't tested).  Could you try the latest release to see if this still happens?

**Comment by jakemcarthur** [comment] 2017-04-28 12:31
First time commenting on this, but I was watching the issue. I had this problem before (in Spacemacs, if it matters), but it seems fixed for me now.

**Comment by tddsg** [comment] 2017-04-29 02:30
@Fuco1 : I've just upgraded the newest smartparens, and enable the comment symbols `(* *)` as a local pair. 

```
(sp-with-modes '(tuareg-mode)
    (sp-local-pair "(*" "*)" ))
```

Everything works just fine, including the parentheses wrapping.

Thank you so much!

**Comment by Fuco1** [comment] 2017-04-29 19:43
Thanks @jakemcarthur and @tddsg for confirmation, I'm closing then.

**Closed by Fuco1** 2017-04-29 19:43 UTC
Labels: bug, specific-mode-support
