### ISSUE TITLE
sp-autoinsert-quote-if-followed-by-closing-pair does not seem to be working

### ISSUE THREAD

**Issue by joca-bt** [Fuco1/smartparens#361] opened 2014-09-16 21:56 UTC
```sp-autoinsert-quote-if-followed-by-closing-pair``` does not seem to be working. ```["asd|]``` always results in ```["asd\"|\"]```, regardless of its value. Tested in Emacs-Lisp mode. See https://github.com/Fuco1/smartparens/wiki/Automatic-escaping#escaping-quotes-before-closing-pair

https://github.com/Fuco1/smartparens/wiki/Automatic-escaping#escaping-quotes-when-wrapping-with-a-quote-pair also seems to not be functioning. (With ```sp-autoescape-string-quote``` set to ```t```.)

**Comment by Fuco1** [comment] 2015-01-17 20:30
Can you try the latest master? I've reworked some pair insertion routines, it should theoretically work now.

I still can't reproduce the issue though.

**Comment by joca-bt** [comment] 2015-02-22 00:51
(setq sp-autoescape-string-quote t
          sp-autoinsert-quote-if-followed-by-closing-pair nil)
    "asd| -> "asd"|"
    ["asd|] -> ["asd"|"]


    (setq sp-autoescape-string-quote t
          sp-autoinsert-quote-if-followed-by-closing-pair t)
    "asd| -> "asd"|"
    ["asd|] -> ["asd"|"]

**Comment by Fuco1** [comment] 2015-02-22 09:09
Autoescape was removed from trunk so this can't work.  It will be added later as standalone thing you attach to pairs.

**Comment by Fuco1** [comment] 2016-05-21 11:08
Works on master with -nw -q so I'm closing this issue.

**Closed by Fuco1** 2016-05-21 11:08 UTC
Labels: bug
