### ISSUE TITLE
Smartparens and Company in Elixir-Mode not pairing 'def'

### ISSUE THREAD

**Issue by jojojames** [Fuco1/smartparens#723] opened 2017-03-30 01:53 UTC
## Expected behavior
Using company with smartparens expands smartparen pairs (or triggers post completion) when appropriate.

## Actual behavior
Pressing [RET] calls company's completion, but Smartparens does not auto-insert ending pair. (Ruby Mode/Elixir Mode)

Pressing [SPACE] cancels company's completion while also skipping Smartparen's space post handler.

## Steps to reproduce the problem
```
  (define-key company-active-map (kbd "RET")
    'jojo/company-complete-selection-or-abort-if-same-unless-yas)
  (define-key company-active-map [return]
    'jojo/company-complete-selection-or-abort-if-same-unless-yas)

  ;; Clipped out a bunch of code for brevity.
  (defun jojo/company-complete-selection-or-abort-if-same-unless-yas ()
    ""
    (interactive)
    (company-complete-selection)))

```
Type 'def', company will pop up a list of completions. Type RET or SPACE to see that nothing happens on SmartParens' side. 

Disable company-mode and trying that same thing makes it work. (Smartparens triggers normally).

## Environment & version information

- `smartparens` version: Latest 2017~
- Active major-mode: Elixir Mode
- Emacs version (`M-x emacs-version`): 25
- OS: OSX

## Current workaround, possible fix?

Definitely hacky workaround but is working for me right now.

This will before the RET case.
```
(defun jojo/company-complete-selection-or-abort-if-same-unless-yas ()
  "Complete selection or abort if prefix matches selection.
If backend is yasnippet, complete normally."
  (interactive)
  (if (and
       ;; Completion is not from Yasnippet.
       (not (eq 'company-yasnippet
                (get-text-property 0 'company-backend
                                   (nth company-selection company-candidates))))
       ;; Completion result is the same as the prefix.
       (string-equal company-prefix
                     (nth company-selection company-candidates)))
      (jojo/company-complete-and-newline)
    (company-complete-selection)))

(defun jojo/company-complete-and-newline ()
  "Complete the current company selection and then go to the next line.
If `smartparens-mode' is enabled, try to insert a matching pair."
  (interactive)
  (company-complete-selection)
  (when (eq 'sp-insert-pair-delayed
            (sp-insert-pair))
    (insert-ret)))

;; Very hacky way to manually make it seem like the RET key was pressed.
;; Had to manually remove the ^M that appears after using the ?\r key.
(defun insert-ret ()
  "Insert a RET as if the user pressed the RET key."
  (interactive)
  (let ((command (key-binding "?\r")))
    (setq last-command-event ?\r)
    (setq this-command command)
    (call-interactively 'self-insert-command)
    (delete-trailing-whitespace (beginning-of-line) (end-of-line)))
  (call-interactively (global-key-binding (kbd "RET"))))
```

^ Might be a lot of code, but the gist of it is that 'def' is generally going to be a completion candidate, if it's the same candidate, I usually want to newline instead of complete (the prefix is the same as the candidate, so nothing happens).

This is for the SPC case.
```
(advice-add 'company-cancel :around #'jojo/sp-insert-pair-after-company-cancel)

(defun jojo/sp-insert-pair-after-company-cancel (orig-fun &rest args)
  "Trigger `sp-insert-pair' when `company-mode' skips completion."
  (interactive)
  ;; This gets called very often so leaving some notes here with timing info.
  (if (and (and smartparens-mode (eq (car args) 'non-unique))
           (string-equal " " (string (preceding-char))))
      ;; Quickly profiling returns 0.002467 ~2ms.
      (progn
        (delete-char -1)
        (sp-insert-pair) ;; Returns `sp-insert-pair-delayed'.
        (insert-char ?\s 1)
        (let ((res (apply orig-fun args)))
          (delete-char -1)
          (insert-space)
          res))
    ;; 0.000413 -> ~.4 ms
    (apply orig-fun args)))

;; https://stackoverflow.com/questions/18905382/how-to-emulate-a-specific-key-press-in-emacs-lisp
(defun insert-space ()
  "Insert a space as if the user pressed the space bar."
  (interactive)
  (let ((command (key-binding " ")))
    (setq last-command-event ?\s)
    (setq this-command command)
    (call-interactively command)))
```

As you can tell, the workaround code is relatively messy (emulating keypresses, etc). It would be good to have some better synergy between company and smartparens. (I did notice there was already an advice in smartparens to handle company but that doesn't seem to help).

**Comment by Fuco1** [comment] 2017-03-30 08:38
The problem is that the smartparens pairs are conditional on `SPC`, `RET` or `<evil-ret>`, so they probably don't get triggered after company because it sends some other input inbetween.

Luckily, you can also trigger insertions on *commands*, so it should be possible to modify the SP pair definitions to do just that.

From the docs:

```
When clause also supports a special format for delayed insertion.
The condition is a list with commands, predicates (with three
arguments as regular when form) or strings specifying the last
event.  All three types can be combined in one list.  The pair
will be inserted *after* the next command if it matches the any
command on the list, if the last event matches any string on the
list or if any predicate returns true.  If the pair's :when
clause contains this special form, it will never be immediately
inserted and will always test for delayed insertion.
```

If the command matching wouldn't work, then you can write your own predicate to test what happened and possibly expand.

```
(sp-local-pair "defmodule" "end"
                 :when '(("SPC" "RET" "<evil-ret>" PUT-EXTRA-COMMANDS-OR-CALLBACKS-HERE))
                 :post-handlers '(sp-elixir-do-block-post-handler))
```

**Comment by Fuco1** [comment] 2024-03-30 18:18
I'm going to close this ticket, the packages changed a lot in the meantime and it's not clear what is the desired outcome, considering lsp mode, company, yasnippet and smartparens can all work at the same time.

**Closed by Fuco1** 2024-03-30 18:18 UTC
Labels: specific-mode-support
