### ISSUE TITLE
Movement staying strictly on same depth level

### ISSUE THREAD

**Issue by sjlnk** [Fuco1/smartparens#623] opened 2016-06-27 11:31 UTC
I think it would be very helpful for exploring code to have an ability to move forward/backward sexps but strictly retain the depth level. Sometimes it's hard to see the structure on Lisp code with naked eye but it could be empirically solved by moving to a certain depth level and then moving sideways to see what is in that particular depth level.

Now we have commands like `sp-next-sexp`, `sp-previous-sexp`, `sp-forward-sexp` and `sp-backward-sexp`. These are great but it would be even nicer if we had a similar function that would not jump to a higher depth level when moving past the last element of that particular depth level. The function could roll back to the first/last element of that depth level or do simply nothing.

If my description isn't clear enough please let me know, I'll post a video illustrating what I tried to explain.

How hard would it be to implement this?

**Comment by Fuco1** [comment] 2016-06-27 16:01
Is this what you mean? (`sp-beginning-of-next-sexp`)

```elisp
"Jump to the beginning of next sexp on the same depth.

This acts exactly as `sp-beginning-of-sexp' but adds 1 to the
numeric argument.

Examples:

  (f|oo) (bar) (baz) -> (foo) (|bar) (baz)

  (f|oo) (bar) (baz) -> (foo) (bar) (|baz) ;; 2"
```

**Comment by azyr** [comment] 2016-06-28 04:39
No, that's not what I meant.

I'll give you some examples:

We have a sexp with 3 depth levels. The number suffix on each expression denotes the depth level.

``( x1 y1 (a2 b2 c2) (d2 e2 f2 (g3 h3) ) )``

Pipeline denotes cursor position.

We have two new commands ``next-parallel-sexp`` and ``previous-parallel-sexp``.

Command sequence 1:

``( x1 y1 (|a2 b2 c2) (d2 e2 f2 (g3 h3) ) )``

``m-x next-parallel-sexp``

``( x1 y1 (a2 |b2 c2) (d2 e2 f2 (g3 h3) ) )``

``m-x next-parallel-sexp``

``( x1 y1 (a2 b2 |c2) (d2 e2 f2 (g3 h3) ) )``

``m-x next-parallel-sexp``

``( x1 y1 (a2 b2 |c2) (d2 e2 f2 (g3 h3) ) )  ; nothing happens``

Command sequence 2:

``( |x1 y1 (a2 b2 c2) (d2 e2 f2 (g3 h3) ) )``

``m-x next-parallel-sexp``

``( x1 |y1 (a2 b2 c2) (d2 e2 f2 (g3 h3) ) )``

``m-x next-parallel-sexp``

``( x1 y1 |(a2 b2 c2) (d2 e2 f2 (g3 h3) ) )``

``m-x next-parallel-sexp``

``( x1 y1 (a2 b2 c2) |(d2 e2 f2 (g3 h3) ) )``

``m-x next-parallel-sexp``

``( x1 y1 (a2 b2 c2) |(d2 e2 f2 (g3 h3) ) )  ; nothing happens``

---------

So we stay strictly in the same depth level, never jumping down or up, even if it means we would do nothing. I think this would make code exploration much easier. Sometimes code is not perfectly indented.

**Comment by Wilfred** [comment] 2016-07-15 21:40
FWIW, I believe lispy's commands offer this: `j` and `k` (`special-lispy-down` and `special-lispy-up`: despite the names, these don't change depth).

**Comment by Fuco1** [comment] 2016-07-18 10:23
@Wilfred home come you know what lispy does?! HERETIC!

Nah.  This sounds like a good idea, we should have someone implement it :D

**Comment by cruegge** [comment] 2016-08-02 22:15
For `sp-forward-sexp`, a quick way to do something similar would be to replace the `(setq ok (sp-get-thing))` part by something like
```
(setq ok (let ((thing (sp-get-thing)))
           (and (or (not (< (sp-get thing :beg) (point) (sp-get thing :end)))
                    (string= (sp-get thing :cl) ""))
                thing)))
```
This checks whether point is inside `thing`, and whether `thing` has a closing delimiter (i.e. is a balanced expression), and stops in that case. So from `(a b |c)` you would first go to `(a b c|)` and then stop, but I think that's generally more useful than trying to stop at `(a b |c)` anyway, e.g. if you want to navigate past `c` to add a `d` there.

Incidentally, this is actually in line with Emacs' own `forward-sexp`, which raises an error in that situation.

The question, if this is a suitable approach, would be whether to modify `sp-forward-sexp` directly (making the change depend on some `defcustom`), or to provide a new function which can then be bound to `C-M-f` instead? The first option is simpler, but I'm not sure it won't break other stuff in unexpected ways. In particular, it breaks the "up one level" behaviour of `sp-next-sexp`, which may or may not be what was intended.

**Comment by Fuco1** [comment] 2016-08-03 10:43
I made `sp-forward-sexp` the way it is specifically because I hated the fact that `forward-sexp` throws an error.  So I would prefer a different function.

**Closed** 2017-04-22 17:29 UTC
Labels: enhancement

**Comment by Fuco1** [comment] 2017-04-22 17:33
The commands `sp-forward-parallel-sexp` and `sp-backward-parallel-sexp` implement the requested functionality.

**Comment by sjlnk** [comment] 2017-04-23 05:23
Wonderful, thanks!
