### ISSUE TITLE
smartparens inserts extra parenthesis into yasnippet expanded via auto-complete

### ISSUE THREAD

**Issue by NateEag** [Fuco1/smartparens#419] opened 2015-01-14 21:55 UTC
I'm not sure which package this bug is really in.

However, it only started happening after I updated to `smartparens-20150111.926` from MELPA, so I'm reporting it here.

Recipe (using `smartparens-20150112.902`, `js2-mode-20141230.717`, `yasnippet-20141223.303`, and `auto-complete-20141228.633` installed from MELPA in `~/.emacs.d/elpa`):

```bash
$ cd ~/.emacs.d
$ emacs -Q
 ```

I put this in the `*scratch*` buffer

```elisp
(normal-top-level-add-subdirs-to-load-path)

(require 'js2-mode)
(require 'smartparens)
(require 'yasnippet)
(require 'auto-complete)
(require 'auto-complete-config)

(switch-to-buffer "test.js")
(js2-mode)
(yas-reload-all)
(yas-minor-mode)
(smartparens-mode)
(auto-complete-mode)

(add-to-list 'ac-sources 'ac-source-yasnippet)
```

then do `M-x eval-buffer`.

In `test.js`, I type `if` then press Tab. I get the following output:

```
if ()condition) {
    
}
```

Note that the snippet is expanded in an unfinished state.

If I delete the buffer's contents, turn off auto-complete-mode (`M-x auto-complete-mode`), and type `if` and press Tab, I get the correct result:

```
if (condition) {

}
```

with `condition` selected and ready for the snippet to progress.

Desktop is OS X 10.10.1, and `M-x emacs-version` says `GNU Emacs 24.4.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2014-10-20 on builder10-9.porkrind.org`.

**Comment by Fuco1** [comment] 2015-01-14 22:00
Well it's definitely smartparents update doing this, but most likely due to bad implementation of `ac`'s insert or expansion.  If they use some hooks or rebind keys in silly ways, this is going to happen.

In the last couple commits I've removed about 500 lines of cruft and hacks from SP that tried to fix other packages' bullshit :P things are going to break for a while since I (or others) figure out how to make it coexist.

**Comment by NateEag** [comment] 2015-01-14 22:03
Okay, thanks for the explanation.

Should I report this on auto-complete's bug tracker?

**Comment by Fuco1** [comment] 2015-01-14 22:07
Dunno as I'm not sure how all this interacts.  Plus AC is rather famous for ignoring bug reports anyway ~_~ I have some time set aside this weekend to go over all the bugs reported about the latest rewrite (see commits tagged with 1.7 milestone), I'll know more then.

MELPA should be considered bleeding edge and "dangerous" for normal use. If you want stable(ish) version, check out the latest 1.6.4 tag.

**Comment by NateEag** [comment] 2015-01-14 22:24
Okay, thanks again. For the moment I've just rolled back to the last MELPA version that didn't have this behavior.

**Comment by Fuco1** [comment] 2016-04-07 19:59
I have this same issue with company, it seems it uses yas under the hood... I'm cleaning this up for the 1.7 milestone so we'll see.  I might need someone to test against AC as I haven't that set up.

**Comment by Fuco1** [comment] 2016-04-08 17:44
Ok, so my company mode issue was something else.  I reproduced this with ac/yasnipet and sp and it works fine in js2-mode.  I'm going to close this.  If you happen to still have this problem feel free to reopen.

**Closed by Fuco1** 2016-04-08 17:44 UTC
Labels: bug
