### ISSUE TITLE
Incompatibility with copilot.el

### ISSUE THREAD

**Issue by JP-Ellis** [Fuco1/smartparens#1145] opened 2023-02-14 10:06 UTC
## Background

[copilot.el](https://github.com/zerolfx/copilot.el) is an implementation of GitHub's [Copilot](https://github.com/features/copilot) which uses an AI to provide completions. Here is an example of it in action:

![](https://raw.githubusercontent.com/zerolfx/copilot.el/main/assets/demo.gif)

The issue has been reported in the copilot repo as well: zerolfx/copilot.el#86

## Expected behavior

Ideally, smartparens-mode and copilot-mode should be able to coexist and work seemlessly with each other.

Specifically, if a completion is being suggested by copilot-mode, pressing `tab` should accept the completion suggested by copilot.

## Actual behavior

When smartparens-mode is enabled, it shadows the `tab` keybinding from copilot, leading to unexpected behaviour. To be specific for a few cases I have identified:

- Completions work fine if there are no trailing closing parenthesis (both with and without `smartparens-mode`)
  ```rust
  impl error::Error for StepError {
      fn <TAB>
  }
  ```

- Completion fails if I have just inserted an opening parenthesis:
  ```rust
  impl error::Error for StepError {
      fn source(<TAB>
  }
  ```
    Instead of accepting the completion, `<TAB>` ends up inserting additional closing parenthesis with the result becoming:
  ```rust
  impl error::Error for StepError {
      fn source()))
  }
  ```

  Note that with the above, it only works when I have a 'pending' closing parenthesis (not sure how `smartparens-mode` calls that internally). So for example, if the code was already `fn source()` and I place my cursor in the middle of `()` and try and get a code completion, I am able to access the completion fine.

## Steps to reproduce the problem

My current example is using Doom Emacs. I haven't had a chance to extensively reproduce a minimal example (might get a chance this weekend 🤞). My full doom configuration is [on GitHub](https://github.com/JP-Ellis/dotfiles/tree/main/doom) but I suspec the relevant parts are relevant:

<details>
<summary><code>init.el</code></summary>

```elisp
;; Redacted to just what I suspect is relevant
 :completion
 (company                      ; the ultimate code completion backend
  +childframe)
 :config
 (default                      ; Reasonable default
   +bindings                   ; Doom's default keybindings
   +smartparens)               ; Doom's configuration for smartparesn
```

</details>

<details>
<summary><code>packages.org</code></summary>

```elisp
(package! copilot
  :recipe (:host github :repo "zerolfx/copilot.el" :files ("dist" "*.el")))
```

</details>

<details>
<summary><code>config.org</code></summary>

```elisp
(use-package! copilot
  :hook (prog-mode  . copilot-mode)
  :bind (("C-TAB"   . 'copilot-accept-completion-by-word)
         ("C-<tab>" . 'copilot-accept-completion-by-word)
         :map copilot-completion-map
         ("<tab>"   . 'copilot-accept-completion)
         ("TAB"     . 'copilot-accept-completion)))
```

</details>

## Environment & version information

**In recent enough `smartparens` you can call `M-x sp-describe-system` to generate this report**.  Please fill manually what we could not detect automatically.  Edit the output as you see fit to protect your privacy.

- `smartparens` version: Latest as of writing this
- Active `major-mode`: `python-mode`
- Smartparens strict mode: nil
- Emacs version (`M-x emacs-version`): GNU Emacs 28.2 (build 2, x86_64-w64-mingw32) of 2022-09-14
- Starterkit/Distribution: Doom Emacs (Evil)
- OS: windows-nt (both replicated on Linux as well)

**Comment by Fuco1** [comment] 2023-02-15 16:22
I'm using smartparens and copilot together and never had a problem.  I don't think smartparens does anything to redefine tab key.  The problem is probably with two overlays existing at once and Emacs being confused which keymap to pick.

You can try to bind tab to whatever copilot completion function you want in the `sp-pair-overlay-keymap` map.  This should add the same completion as exists on the copilot overlay to the smartparens overlay as well.


    (define-key sp-pair-overlay-keymap (kbd "TAB") 'copilot-accept-completion)

**Comment by JP-Ellis** [comment] 2023-02-15 23:38
I can confirm this work, thank you! I'll submit a PR to copilot.el in order to update the configuration instructions.

**Comment by ryankhart** [comment] 2023-02-16 00:29
> (define-key sp-pair-overlay-keymap (kbd "TAB") 'copilot-accept-completion)

This is awesome! That works for me too.

I was able to turn back on smartparens after adding this keymap. I've only spent about 30 seconds with it so far, but I assume it works, and if it doesn't, I'll report back here.

For anyone newer to Emacs than me who's confused how to convert this to a Doom Emacs config, here's my updated copilot config for Doom Emacs:
```Elisp
(use-package! copilot
  :hook (prog-mode . copilot-mode)
  :bind* (("<backtab>" . 'copilot-accept-completion-by-word)
          :map copilot-completion-map
          ("<tab>" . 'copilot-accept-completion)
          ("TAB" . 'copilot-accept-completion)
          :map sp-pair-overlay-keymap
          ("<tab>" . 'copilot-accept-completion)
          ("TAB" . 'copilot-accept-completion)))
```

**Comment by Fuco1** [comment] 2023-02-18 20:33
All right, I'll close this then.  Feel free to reopen or add a new issue.  Thanks!

**Closed by Fuco1** 2023-02-18 20:33 UTC
Labels: question, configuration
