### ISSUE TITLE
mismatch parens are still highlighted after toggle smartparens-mode off

### ISSUE THREAD

**Issue by oldk1331** [Fuco1/smartparens#622] opened 2016-06-27 08:35 UTC
Like the title said, in a file with mismatched parens, they're highlighted; but after toggle
smartparens-mode off, the highlights doesn't go away.  Is this a bug or a feature?

**Comment by Fuco1** [comment] 2016-06-27 08:43
I think it's a feature, the highlighting is handled by a separate mode: `show-smartparens-mode` (similar to `show-paren-mode`).  They aren't toggled together so you probably enabled both somewhere.

**Comment by oldk1331** [comment] 2016-06-27 08:49
First, I think I disable both modes in a hook.
Second, toggle `show-smartparens-mode` doesn't make the highlighting go away, is that a bug or feature?

**Comment by oldk1331** [comment] 2016-06-27 08:52
I disabled both modes in A-mode-hook.

I think A-mode-hook calls some B-mode first, then B-mode calls smartparens-mode and highlightings are added, then A-mode-hook disables both mode, but highlightings are remained.

**Comment by Fuco1** [comment] 2016-07-04 19:42
When `show-smartparens-mode` is disabled and there are some smartparens overlays, they are removed.  I can't reproduce this issue and the code is almost 100% correct.

Can you give me some example buffer or something where the behaviour is repeatable?

**Comment by ustcscgy** [comment] 2016-07-05 00:11
I'm using spacemacs.

Open a buffer with smartparens-mode on. Type a `)` first, then every following parenthesis will be highlighted and are not removed by turning off smartparens-mode and show-smartparens-mode.

**Comment by Fuco1** [comment] 2016-07-05 09:14
Can you check what kind of overlay that is?  Put the cursor somewhere on the overlay, then hit `C-u C-x =` and look for the overlays section.

**Comment by ustcscgy** [comment] 2016-07-05 09:37
````
There are text properties here:
  face                 (rainbow-delimiters-unmatched-face)
  fontified            t
````

**Comment by Fuco1** [comment] 2016-07-05 09:53
Then it seems it's not a smartparens problem but rainbow-delimiters problem.

**Comment by ustcscgy** [comment] 2016-07-05 09:55
Oh, sorry.

**Comment by Fuco1** [comment] 2016-07-05 09:58
No problem.

Maybe you should open an issue with spacemacs? This seems like misconfiguration (I don't use spacemacs myself).

I'm going to close this.

**Closed by Fuco1** 2016-07-05 09:58 UTC
Labels: bug

**Comment by ustcscgy** [comment] 2016-07-05 10:02
I will open an issue for spacemacs.  Thanks for your great work.
