### ISSUE TITLE
[ruby-mode] show-smartparens hangs for %w() list

### ISSUE THREAD

**Issue by ddoherty03** [Fuco1/smartparens#365] opened 2014-10-03 12:39 UTC
In the following:

    module Byr
      module Ofx
        #######################################################################
        # Broker Transaction Classes
        #######################################################################
        class BrokerTrans < Trans

          # NOTE: there are 19 different kinds of broker transactions that need to
          # be distinguished.  There are classes for each of them, but until I run
          # into one in the real world, many will remain untested.
          CATEGORIES = %w(buy_debt buy_mf buy_opt buy_other buy_stock closure_opt
                          income inv_expense jrnl_fun jrnl_sec margin_interest
                          reinvest ret_of_cap sell_debt sell_mf sell_opt
                          sell_other sell_stock split inv_bank_trans)^
        end
      end
    end

when cursor is at end of CATEGORIES list (shown by ^), show-smartparens causes emacs to
hang in ruby-mode.

**Comment by Fuco1** [comment] 2016-06-14 11:08
Update: currently it incorrectly highlights the inner-most class/end.

The problem is that `%w` makes the `()` into a string, and because the cursor *after* `)` is in "code context" it skips over the string.

What we need to do is to also check what the context of the closing paren to the right is, and then navigate that to the opening `(` instead (cf. the same problem with closing comment syntax).

**Closed** 2016-06-14 19:49 UTC
Labels: bug
