### ISSUE TITLE
sp-kill-sexp only kills the first character when used on some clojure sexps

### ISSUE THREAD

**Issue by djr7C4** [Fuco1/smartparens#672] opened 2016-11-06 20:00 UTC
For example, in clojure mode, the following is a complete sexp (literal syntax for a regexp)

    |#""

However, running sp-kill-sexp only kills the preceeding '#'.

-->

    |""

In the following case, it ignores the hash

    #|""

-->

    |#

For the #' prefix, only the hash is killed

    |#'x

-->

    |'x

However, when the point is forward one character the entire sexp is correctly killed.

    #|'x

-->

    |

As near as I can tell (without being too familiar with the implementation of smartparens) the issue (in case of the regexp syntax #"") actually occurs in sp-get-thing when it is called from sp-forward-sexp (which is called from sp-kill-sexp).  Namely, sp-get-thing seems to handle strings using the following chunk of code which checks if it is at the start of a string without first skipping over any prefix characters.

                 ((and (eq (char-syntax (preceding-char)) 34)
                       (not (sp-char-is-escaped-p (1- (point)))))
                  (if (eq t (sp-point-in-string))
                      (sp-get-stringlike-expression t)
                    (sp-get-string t)))

This appears to be related to #593 (which mentions the two cases above).

**Comment by Fuco1** [comment] 2017-07-13 18:03
This was fixed by #593.  The behaviour when the point is between the prefix and the sexp killing only the sexp is by design, often you want to keep the prefix and just change the body.  When killing from the front it removes everything.

**Closed by Fuco1** 2017-07-13 18:03 UTC
Labels: bug, specific-mode-support
