### ISSUE TITLE
show-smartparens-mode not working when cursor on right parenthesis

### ISSUE THREAD

**Issue by et2010** [Fuco1/smartparens#758] opened 2017-06-19 02:13 UTC
## Expected behavior
Left matching parenthesis should be highlighted when the cursor is on the right parenthesis.

## Actual behavior
Left parenthesis is not highlighted, see the fig below:

![image](https://user-images.githubusercontent.com/11584902/27266899-2939e82c-54d7-11e7-95a6-a723d3e4381c.png)

Note that when the cursor is on the left parenthesis, the highlighting works as expected:

![image](https://user-images.githubusercontent.com/11584902/27266951-96308ea4-54d7-11e7-9041-f45b3c5843d3.png)

## Steps to reproduce the problem
Just open any elisp buffer and move the cursor as described above. Make sure the built-in `show-paren-mode` is off.

**Edit:** I'm using evil-mode, above repro guide is for the 'normal' state. For emacs state, to reproduce, you should move the cursor to the point before the right parenthesis.

## Environment & version information

- `smartparens` version: smartparens-20170618.744
- Active major-mode: emacs-lisp-mode
- Emacs version (`M-x emacs-version`): GNU Emacs 25.2.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.10) of 2017-04-22
- OS: Archlinux

**Comment by Fuco1** [comment] 2017-06-19 08:11
Try to set `sp-show-pair-from-inside` to `t`.

The problem is that vim and emacs handle the point differently.  In vim cursor is *on* the character while in emacs cursor is *between* characters, so even if it actually draws on top it is in reality between that and the previous char.

We only highlight the pair backwards if the closing delimiter is the *previous* character.

**Comment by et2010** [comment] 2017-06-19 12:48
Thanks for clarifying. I still observed the same behavior after setting `sp-show-pair-from-inside` to `t`. Restarting emacs after setting the variable didn't work either.

**Comment by et2010** [comment] 2017-06-21 02:11
It seems that setting `sp-show-pair-from-inside` to `t` doesn't work anymore, is it a bug or just me? @Fuco1

**Comment by therockmandolinist** [comment] 2017-06-21 04:39
Same issue here - to clarify, this is only an issue in normal mode. @Fuco1 would it be possible to add a `(when featurep 'evil)` or similar that checks if in `evil-normal-state` and changes the behavior for the closing delimiter?

**Comment by Fuco1** [comment] 2017-06-21 08:00
We have that already

```elisp
(and (or (sp--evil-normal-state-p)
         (sp--evil-motion-state-p)
         (sp--evil-visual-state-p))
     (sp--looking-at (sp--get-allowed-regexp)))
```

There's probably some other issue /shrug

**Comment by Fuco1** [comment] 2017-06-23 20:14
I have tried this just now with the latest evil from melpa, latest smartparens on emacs 25.2.1 and I can not reproduce the problem.  I have the exact same text as on the screenshot and it highlights as expected

![](http://i.imgur.com/DuZ0P5L.png)

Can you try this without spacemacs, just with evil mode and smartparens loaded?

**Comment by et2010** [comment] 2017-06-24 01:19
I tried stock emacs with only evil and smartparens loaded, but the issue persists:

![sp](https://user-images.githubusercontent.com/11584902/27504529-fa34d682-58bd-11e7-8ec3-9a885701ae92.gif)

**Comment by Fuco1** [comment] 2017-06-24 12:05
Should be fixed in master.

**Closed** 2017-06-24 12:04 UTC
Labels: evil

**Comment by et2010** [comment] 2017-06-24 12:24
Thanks!
