### ISSUE TITLE
smartparens appears to have performance issues that make my typing very slow

### ISSUE THREAD

**Issue by jowens** [Fuco1/smartparens#595] opened 2016-04-20 16:56 UTC
I am editing LaTeX text; typing is very slow and does not reflect characters as I type. Among my minor modes are "Show-Paren Show-Smartparens Show-Smartparens-Global Smartparens" (not sure if these are all smartparens packages, just making sure).

This is GNU Emacs 25.0.92.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1603)) of 2016-03-02 [from emacsformacox.com; this problem was also present in the last OS X emacs release, however]. package-list-packages indicates I'm running `smartparens        20160411.719`.

I ran the profiler while I was typing LaTeX. CPU time appears to be going disproportionally to `sp--post-self-insert-hook-handler`, so perhaps it could be the culprit?

```
 command-execute                                               24378  97%
 - call-interactively                                           24378  97%
  - funcall-interactively                                       24091  96%
   - self-insert-command                                        23813  95%
    - sp--post-self-insert-hook-handler                         23801  95%
     - sp--all-pairs-to-insert                                  11963  47%
      + sp--looking-back-p                                      11822  47%
      + sp--do-action-p                                            68   0%
        sp--strict-regexp-quote                                    55   0%
     + sp-insert-pair                                           11775  47%
     + sp-skip-closing-pair                                        29   0%
    + flycheck-handle-change                                        7   0%
    + expand-abbrev                                                 3   0%
    + jit-lock-after-change                                         2   0%
```

**Comment by Lompik** [comment] 2016-04-28 19:46
How recent is the computer ? Is this a regression ? How fast do you type ?

I tested on Linux and I do have the same of kind distribution in the cpu % but not the same amount. It does not feel slow. Looking at the profiling in details, from `smartparens` standpoint:

  - 23% in `sp--post-self-insert-hook-handler`
  - 22% `sp-insert-pair`

BUT most of this time is spend in underlying emacs functions, namely `texmathp`, `syntax-ppss` both in each above functions. I am not familiar with the code but hope this can help someone who is.


    - command-execute                                                8038  51%
     - call-interactively                                            8038  51%
      - funcall-interactively                                        7513  47%
       - self-insert-command                                         7389  47%
        - sp--post-self-insert-hook-handler                          7356  46%
         - sp--all-pairs-to-insert                                   3733  23%
          - sp--do-action-p                                          3549  22%
           - run-hook-with-args-until-success                        1335   8%
            - sp-in-math-p                                           1223   7%
     7%-->   + texmathp                                              1213   7%
            + sp-latex-point-after-backslash                          105   0%
           - sp-point-in-string                                       966   6%
     5%-->  + syntax-ppss                                             929   5%
           - sp-point-in-comment                                      951   6%
     5%-->    syntax-ppss                                             894   5%
              syntax-after                                             10   0%
           + sp-get-pair                                              237   1%
           + -flatten                                                  20   0%
          + sp--looking-back-p                                        143   0%
            sp--strict-regexp-quote                                    20   0%
         - sp-insert-pair                                            3565  22%
          - sp--pair-to-insert                                       3562  22%
           - sp--all-pairs-to-insert                                 3537  22%
            - sp--do-action-p                                        3231  20%
             - run-hook-with-args-until-success                       976   6%
              - sp-in-math-p                                          934   5%
      5%-->    + texmathp                                             934   5%
              + sp-latex-point-after-backslash                         42   0%
             - sp-point-in-comment                                    940   6%
      5%-->     syntax-ppss                                           888   5%
                syntax-after                                           10   0%
             - sp-point-in-string                                     908   5%
      5%-->     syntax-ppss                                           884   5%
             + sp-get-pair                                            342   2%
             + -flatten                                                42   0%
            + sp--looking-back-p                                      203   1%
              sp--strict-regexp-quote                                  41   0%
         + sp-skip-closing-pair                                        23   0%
        + do-auto-fill                                                 14   0%
        + jit-lock-after-change                                        13   0%
       + previous-line                                                 54   0%
       + TeX-insert-backslash                                          11   0%
       + helm-M-x                                                       6   0%
       + TeX-insert-quote                                               6   0%
       + quit-window                                                    4   0%
      + byte-code                                                     525   3%
    + delete-selection-pre-hook                                      3862  24%

**Comment by Nielius** [comment] 2016-04-29 20:05
I may have the same problem. I'm running an oldish Lenovo Thinkpad T61 and emacs takes a really long time (several seconds, so even a hunt-and-peck-typer would have problems) to process something as simple as typing ```(make-auto-save-file-name)``` in a small elisp file (<100 lines):

```
- command-execute                                               20509  84%
 - call-interactively                                           20459  84%
  - funcall-interactively                                       19411  80%
   - self-insert-command                                        10642  43%
    - sp--post-self-insert-hook-handler                         10642  43%
     - sp-insert-pair                                            5531  22%
      - sp--pair-to-insert                                       5126  21%
       - sp--all-pairs-to-insert                                 5116  21%
        - sp--looking-back-p                                     5107  21%
         - sp--looking-back                                      4620  19%
            sp--looking-at                                          7   0%
           #<compiled 0x2b3d647>                                    4   0%
        + sp--do-action-p                                           5   0%
          sp--strict-regexp-quote                                   4   0%
      + sp--pair-to-uninsert                                      405   1%
     - sp--all-pairs-to-insert                                   5111  21%
      - sp--looking-back-p                                       5111  21%
       - sp--looking-back                                        4642  19%
          sp--looking-at                                            3   0%
         #<compiled 0x2b3d647>                                      4   0%
   + file-notify-handle-event                                    7947  32%
   + newline-and-indent                                           745   3%
```

It seems ```sp--looking-back``` is problematic.

I'm using GNU Emacs 25.1.50.2 (i686-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-04-25 on Kubuntu 16.04 and the same version of smartparens (20160411.719).

**Comment by Fuco1** [comment] 2016-04-29 20:10
@Lompik what emacs version do you run? I see that both of you with the slowness issue are on emacs 25, so I suspect that is somehow related.

I run 24 and don't experience these issues.  I will set up a virtual or something with e25 and try it there.

**Comment by Nielius** [comment] 2016-04-29 20:46
Another interesting case: I even have problems when I open an empty buffer with a .el-extension (so that the relevant packages and options are set) and type something that doesn't even involve a bracket. This is what my profiles gives me:

```
- command-execute                                               11206  95%
 - call-interactively                                           11201  95%
  - funcall-interactively                                        8257  70%
   - self-insert-command                                         3939  33%
    - sp--post-self-insert-hook-handler                          3939  33%
     - sp-insert-pair                                            1989  17%
      - sp--pair-to-insert                                       1989  17%
       - sp--all-pairs-to-insert                                 1989  17%
        - sp--looking-back-p                                     1976  16%
         + sp--looking-back                                      1778  15%
        + sp--do-action-p                                           3   0%
     - sp--all-pairs-to-insert                                   1950  16%
      - sp--looking-back-p                                       1937  16%
       + sp--looking-back                                        1695  14%
      + sp--do-action-p                                            10   0%
   - file-notify-handle-event                                    3739  32%
    - file-notify-callback                                       3726  31%
       file-notify--event-file-name                                70   0%
       auto-revert-notify-handler                                  12   0%
   + helm-M-x                                                     568   4%
   + evil-normal-state                                             11   0%
  + byte-code                                                    2941  25%
```

**Comment by Lompik** [comment] 2016-04-30 04:59
yes above test was with emacs-25.1.50 but like I said i don't experence slowness but same cpu ressources usage.

here's the result on 24.5 with (`sp-insert-pair` at 22% and `sp--all-pairs-to-insert` at 17%) :

    - command-execute                                                1066  44%
     - call-interactively                                            1066  44%
      - self-insert-command                                           996  41%
       - sp--post-self-insert-hook-handler                            983  40%
        - sp-insert-pair                                              549  22%
         - sp--pair-to-insert                                         545  22%
          - sp--all-pairs-to-insert                                   534  22%
           - sp--do-action-p                                          442  18%
            - sp-point-in-string                                      183   7%
             + syntax-ppss                                            178   7%
            - sp-point-in-comment                                     163   6%
             + syntax-ppss                                            145   6%
               syntax-after                                             4   0%
            - sp-get-pair                                              44   1%
               sp--get-pair-definition                                 37   1%
            + -flatten                                                 24   0%
           - sp--looking-back-p                                        71   2%
            - sp--looking-back                                         23   0%
               sp--looking-at                                          20   0%
             sp--strict-regexp-quote                                    9   0%
        - sp--all-pairs-to-insert                                     412  17%
         - sp--do-action-p                                            201   8%
          - sp-point-in-string                                         89   3%
           + syntax-ppss                                               89   3%
          - sp-point-in-comment                                        60   2%
           + syntax-ppss                                               60   2%
          + -flatten                                                   17   0%
          - sp-get-pair                                                11   0%
             sp--get-pair-definition                                    7   0%
         - sp--looking-back-p                                         179   7%
          - sp--looking-back                                           73   3%
             sp--looking-at                                            49   2%
           sp--strict-regexp-quote                                     29   1%
        - sp-skip-closing-pair                                         14   0%
           sp--char-is-part-of-stringlike                               4   0%
           sp--single-key-description                                   4   0%
           sp--char-is-part-of-closing                                  3   0%
         jit-lock-after-change                                          3   0%
      + byte-code                                                      33   1%
      + minibuffer-complete                                            19   0%
      + execute-extended-command                                       12   0%
      + fill-paragraph                                                  6   0%
    + redisplay_internal (C function)                                 930  38%

**Comment by jowens** [comment] 2016-05-01 16:45
Sorry for the delay. I have a 2013 MacBook Pro; it's pretty fast. I have used smartparens successfully in previous emacsen; this might be an emacs 25 issue? I am not a particularly fast typer. Any large fraction of runtime in `sp--post-self-insert-hook-handler` does, unfortunately, feel like an actual issue.

**Comment by aaronjensen** [comment] 2016-05-16 02:57
I'm on emacs 25 on a 2013 MacBook Pro and smartparens makes typing frustratingly slow. Here's a profile for me:

```
- command-execute                                                 260  62%
 - call-interactively                                             260  62%
  - funcall-interactively                                         260  62%
   - self-insert-command                                          248  59%
    - sp--post-self-insert-hook-handler                           247  59%
     - sp--all-pairs-to-insert                                    132  31%
      + sp--looking-back-p                                        100  23%
      + sp--do-action-p                                            30   7%
        sp--strict-regexp-quote                                     2   0%
     - sp-insert-pair                                             110  26%
      - sp--pair-to-insert                                        109  26%
       - sp--all-pairs-to-insert                                  107  25%
        + sp--looking-back-p                                       74  17%
        + sp--do-action-p                                          27   6%
          sp--strict-regexp-quote                                   5   1%
     - sp-skip-closing-pair                                         4   0%
        sp--char-is-part-of-closing                                 2   0%
        sp--char-is-part-of-stringlike                              1   0%
    + expand-abbrev                                                 1   0%
   + evil-normal-state                                              7   1%
   + profiler-report                                                3   0%
   + evil-insert                                                    2   0%
+ timer-event-handler                                             103  24%
+ redisplay_internal (C function)                                  34   8%
+ evil-escape-pre-command-hook                                     15   3%
+ ...                                                               3   0%
+ sp--save-pre-command-state                                        1   0%
+ yas--post-command-handler                                         1   0%
+ flycheck-handle-signal                                            1   0%
```

If it helps, this typing was in this js2-mode file:

```js
import babel from 'rollup-plugin-babel';
import multiEntry from 'rollup-plugin-multi-entry';
import commonjs from 'rollup-plugin-commonjs';
import nodeResolve from 'rollup-plugin-node-resolve';
import whatever from 'whatever; // this is more or less what I typed to generate the profile

export default {
  entry: 'test/**/*-spec.js',
  plugins: [
    babel(),
    multiEntry(),
    nodeResolve({
      jsnext: true,
      main: true,
    }),
    commonjs({
      namedExports: {
        'node_modules/chai/index.js': ['expect'],
      },
    }),
  ],
  format: 'iife',
  moduleName: 'updeepTest',
  intro: 'require("source-map-support").install();',
  dest: 'test/karma.js',
  sourceMap: true,
};
```

**Comment by thomasf** [comment] 2016-05-21 20:30
It's probably a emacs25 issue, I upgraded to emacs-25 master a few weeks ago and I have to restart my emacses 0.5-5 times a day.. It's a bit slow all the time but sometimes it just locks my entire emacs
Allmost all cpu time time is spent in `sp--looking-back` (called from various oth

**Comment by Fuco1** [comment] 2016-05-22 08:34
All right then, seems like we will need to dig into the e25 regexps :/

**Comment by aaronjensen** [comment] 2016-06-05 04:25
It may not solve the performance regression, but unless I misunderstand something, it seems like `sp-looking-back` is doing an awful lot of unnecessary work. The default `sp-max-pair-length` is `10` which means that for each pair in `sp-local-pairs`, `sp-looking-back` is doing 10 regex matches. When the large majority of openers are fixed length, this seems unnecessary. If we could configure a length range for each pair, then `sp-looking-back` could do exactly as many regex matches as it needs to. For example, the `"{"` regex will only ever need to be run on 1 character back. It doesn't need to run at 10 different spots. Again though, maybe I'm missing something.

Performance improves greatly when I adjust `sp-max-pair-length` down to `2`, which is sufficient for most openers.

**Comment by Fuco1** [comment] 2016-06-05 09:46
The problem is that you don't know in advance which pair you are checking.  SP creates a huge regex for all the pairs then runs that to find the first "eligible" pair and then works on that pair only.  Some pairs can also have multiple different openers (ruby's `end` for example).

However, we could shrink the limit after we find what pair(s) we're dealing with and it sounds like a nice optimization indeed.

**Comment by aaronjensen** [comment] 2016-06-05 16:08
> SP creates a huge regex for all the pairs then runs that to find the first "eligible" pair and then works on that pair only

This may be the problem. I'm not seeing this behavior. I'm seeing smartparens check for the huge regex and then every pair. It calls `sp-looking-back` once for each pair.



> However, we could shrink the limit after we find what pair(s) we're dealing with and it sounds like a nice optimization indeed

If it is helpful, the optimization could probably be applied to the large regex as well by taking the max of the maxes & min of the mins and using that as your range. In languages like ruby this wouldn't help much, but it could help in javascript. This may not matter much at all if there's actually a bug as described above.

**Comment by aaronjensen** [comment] 2016-06-08 05:50
@Fuco1 I'm still not sure I understand your comment. When I look at `sp--post-self-insert-hook-handler` it looks like it regex matches every pair twice every insert. I added some messages to it and `sp--looking-back` and the below output is what I got. That's a ton of regex matches. Maybe that was fast in emacs 24, but its not in 25. Is it intentional?

```elisp
(defun sp--post-self-insert-hook-handler ()
  (with-demoted-errors "sp--post-self-insert-hook-handler: %S"
    (when smartparens-mode
      (message "INSERT")
      (let (op action)
        (setq op sp-last-operation)
        (when (region-active-p)
          (sp-wrap--initialize))
        (cond
         (sp-wrap-overlays
          (sp-wrap))
         (t
          (message "t")
          ;; TODO: this does not pick correct pair!! it uses insert and not wrapping code
          (sp--setaction action (-when-let ((_ . open-pairs) (sp--all-pairs-to-insert))
                                  (catch 'done
                                    (-each open-pairs
                                      (-lambda ((&keys :open open :close close))
                                        (--when-let (sp--wrap-repeat-last (cons open close))
                                          (throw 'done it)))))))
          (message "1")
          (sp--setaction action (sp-insert-pair))
          (message "2")
          (sp--setaction action (sp-skip-closing-pair))
          (message "3")
          ;; if nothing happened, we just inserted a character, so
          ;; set the apropriate operation.  We also need to check
          ;; for `sp--self-insert-no-escape' not to overwrite
          ;; it.  See `sp-autoinsert-quote-if-followed-by-closing-pair'.
          (when (and (not action)
                     (not (eq sp-last-operation 'sp-self-insert-no-escape)))
            (setq sp-last-operation 'sp-self-insert))))))))
```

```
"\\(?:\\(?:\\(?:\\\\\\(?:\\\\[()]\\|[(){}]\\)\\|[]()[{}]\\)\\)\\)" [3 times]
INSERT
t
"\\(\\sw\\|\\s_\\)'"
"\\(?:->\\)"
"\\(?:\\<do\\>\\)"
"\\(?:`\\)"
"\\(?:{\\)"
"\\(?:\\[\\)"
"\\(?:(\\)"
"\\(?:'\\)"
"\\(?:\"\\)"
"\\(?:\\\\\"\\)"
"\\(?:\\\\(\\)"
"\\(?:\\\\{\\)"
"\\(?:\\\\\\\\(\\)"
1
"\\(\\sw\\|\\s_\\)'"
"\\(?:->\\)"
"\\(?:\\<do\\>\\)"
"\\(?:`\\)"
"\\(?:{\\)"
"\\(?:\\[\\)"
"\\(?:(\\)"
"\\(?:'\\)"
"\\(?:\"\\)"
"\\(?:\\\\\"\\)"
"\\(?:\\\\(\\)"
"\\(?:\\\\{\\)"
"\\(?:\\\\\\\\(\\)"
```

**Comment by aaronjensen** [comment] 2016-07-09 15:00
FYI, I reported upstream: http://debbugs.gnu.org/cgi/bugreport.cgi?bug=23928

**Comment by aaronjensen** [comment] 2016-07-10 16:03
The performance issue appear to not be a regression in emacs 25. 

Instead, it is an issue with binding `case-fold-search`, which [slows down more the more buffers you have](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=18522#201).

If I avoid binding `case-fold-search` then smartparens hardly shows up on the profile, if at all. 

I would think that `case-fold-search` could be bound *once* at a higher level instead of for every regexp check. This might require a decent amount of shotgun surgery?

**Comment by Fuco1** [comment] 2016-07-10 20:30
That is pretty nasty :O 

We don't need to bind it every time, just for pairs with word letters (which is quite rare as most pairs are symbols).  But that won't help with functions like `sp--looking-at` where you simply don't know the calling context.  Maybe set it somewhere in the top-level functions like `sp-get-thing`... what happens if they are later re-bound down the call stack?  Because those functions are called from many places so we can never be sure... but if binding it somewhere sufficiently "top-level" would stop the overriding, that could help quite a lot.

Maybe we could first test if it is nil and if so don't re-set it... that sounds like a hack but maybe worth a try.

So if you want to give it a go, wrap the entire body of `sp-get-thing` with the let binding and then add a test to `sp--looking-at` and friends to only let bind if the value is not nil.  If you don't know how or are busy let me know I'll try to throw it in a branch.

Thanks for all the work you put into this by the way, I really appreciate it!  After my share of digging in emacs internals I sometimes dread to go back there ;D

**Comment by aaronjensen** [comment] 2016-07-15 01:23
Hey all, my master branch has both #628 and #629 in it to help greatly w/ performance, if you want to give it a try and report back your findings/profiles it'd be appreciated. Thanks!

https://github.com/aaronjensen/smartparens/

**Comment by aaronjensen** [comment] 2016-07-21 22:19
@jowens can you try master? #628 was merged in and should fix the primary perf issue. Maybe we can close this out?

**Comment by thomasf** [comment] 2016-07-22 11:29
I don't really have a particular test case for the set up where I had all the problems, especially since I did not know that the number of open buffers had an effect...

Anyway,, I just opened 100 Python buffers and 100 Go buffers and it seems to work fine even when I insert a lot of very broken pairs at multiple locations in a buffer.

**Comment by Lompik** [comment] 2016-07-23 12:22
I 've been running some tests as well. While I could not see any difference with just one file opened, I've wiped a little perl script to open 300 files and type some text. Only difference between the 2 example below is `smartparens`' git version (not byte compiled). Here's the full profiling information for after 453687e [link](http://sprunge.us/KFCJ) and before 051edfa [link](http://sprunge.us/eXCM). Macros aren't profilable but I hope those tests still make sense.

**Comment by aaronjensen** [comment] 2016-07-23 15:56
@Lompik that looks like a great improvement. Could you also give https://github.com/Fuco1/smartparens/pull/629 a shot and see what that looks like w/ your test? Thanks!

**Comment by Lompik** [comment] 2016-07-23 16:18
@aaronjensen with 0823d01 -> [link](http://sprunge.us/VXDD) :)

**Comment by aaronjensen** [comment] 2016-07-23 16:25
Nice, thanks @Lompik.

**Comment by jowens** [comment] 2016-07-26 00:18
This feels considerably better. It no longer feels laggy. Woo!

```
- command-execute                                                 332  43%
 - call-interactively                                             332  43%
  - funcall-interactively                                         231  30%
   - self-insert-command                                          182  23%
    - sp--post-self-insert-hook-handler                           181  23%
     - sp--all-pairs-to-insert                                     91  11%
      + sp--do-action-p                                            64   8%
      + sp--looking-back-p                                         22   2%
        sp--strict-regexp-quote                                     2   0%
     - sp-insert-pair                                              82  10%
      + sp--pair-to-insert                                         82  10%
     + sp-skip-closing-pair                                         3   0%
      jit-lock-after-change                                         1   0%
```

**Comment by aaronjensen** [comment] 2016-07-26 00:56
Thanks for testing @jowens.

@Fuco1 we can probably consider this closed 🎉 though it'd be great if https://github.com/Fuco1/smartparens/pull/629 could get merged as well.

Thanks!

**Comment by fommil** [comment] 2016-10-27 15:46
this was impacting me today, I was running an old version so upgraded and perf problem is fixed. Thank you, thank you, thank you!

**Comment by Fuco1** [comment] 2016-10-27 16:57
Hm, you're welcome, although I'm not sure what changed to make the issue disappear :D

**Comment by fommil** [comment] 2016-10-27 17:01
I guess it's because the regexp search backwards is now using a quote based approach, which might allow for simple string matching. But that's just a guess... and if that's not what is happening, perhaps this could be a possible further improvement.

**Comment by Fuco1** [comment] 2016-10-27 17:06
Oh yes, I've played with the regexp search functions a bit, there were some subtle bugs so it might've actually fixed some odd edge cases too.  Let's wait for the others to confirm.

**Comment by aaronjensen** [comment] 2016-10-27 17:23
depends on how old his version was. #628 and #629 were both merged and helped immensely. I think this issue is closeable.

**Comment by quanyufang** [comment] 2017-04-26 04:03
add a test case:
`$arr = ((string)$string)`
if delete leftmost parentheses first, then delete rightmost parentheses , will meet a long delay

**Comment by Fuco1** [comment] 2017-04-26 08:34
Thanks everyone who contributed to this, either with testing or with code, both are really appreciated!

**Closed by Fuco1** 2017-04-26 08:34 UTC

**Comment by guraltsev** [comment] 2019-09-25 14:57
I still have this problem in AucTeX. Should I open a new report?

**Comment by Fuco1** [comment] 2019-09-25 17:06
@guraltsev yes please
