### ISSUE TITLE
Smartparens interferes with cua preventing pasting over highlighted region

### ISSUE THREAD

**Issue by pronobis** [Fuco1/smartparens#396] opened 2014-12-13 00:25 UTC
By default, when running `emacs -q`, and invoking `(cua-mode 1)`, `cua-paste` (C-v) will paste over the contents of active region deleting the previous contents and yanking in the contents from the kill ring. However, if now the following code is run:
```
(require 'smartparens-config)
(smartparens-mode 1)
```
then pasting over the region no longer works and the contents of the kill ring is appended after the region.

I'm on Emacs 24.4

**Comment by Fuco1** [comment] 2015-01-01 13:31
Can you guys try the `reworking-input-system` branch to see if the problem is fixed there? I'm throwing away huge chunks of code that is obsolete so it might break some other things though.

**Comment by djl** [comment] 2015-01-01 13:48
The `reworking-input-system` branch has indeed fix my issue from #368. Thanks!

**Comment by Fuco1** [comment] 2015-01-17 20:13
@pronobis @jasonm23 @zoos The patch has been merged to the mainlain. Could you please download the latest git/melpa and see if your problem is fixed? (make sure you have a backup of your current smartparens installation as several things are broken on master)

**Comment by jasonm23** [comment] 2015-01-18 00:06
Thanks @fuco1 can you give us a list of those breakages?

**Comment by Fuco1** [comment] 2015-01-18 08:07
@jasonm23 Well, whatever it was you had a problem with. I suppose that's the OP problem with CUA pasting.

**Comment by jasonm23** [comment] 2015-01-18 08:49
@Fuco1 ... I was referring to this from your previous comment.  

> several things are broken on master

Surely, you just told us that you'd fixed CUA pasting.  Please clarify the things broken on master.

**Comment by Fuco1** [comment] 2015-01-18 08:54
Mostly things I'm rewriting now: wrapping, rewrapping, possibly insertion of some classes of pairs, autoskip, inserting multiple opening delimiters only inserts one closing, many special mode remappings make SP simply not work ( #415 ). See also issues with 1.7 milestone.

**Comment by jasonm23** [comment] 2015-01-18 09:01
Thanks for listing. (I'll keep an eye on the milestone)

**Comment by jasonm23** [comment] 2015-01-18 12:48
@Fuco1  Upgraded my installed Smartparens to latest via Melpa.  Basic tests provide positive indications that paste over a selection is now working properly.

@pronobis suggest you upgrade the package and try it out.

**Comment by jasonm23** [comment] 2015-01-18 14:22
Hi @Fuco1 I found a problem with this fix.  When the selection is deleted before the yank, it isn't part of undo history.

So when undo-ing, the deleted region isn't reverted.

**Comment by Fuco1** [comment] 2015-01-18 14:37
When I select a region and type over, then undo, it pops back. Same when I paste over it.

Can you write more detailed steps on how to reporduce it?

**Comment by jasonm23** [comment] 2015-01-18 14:42
Will do tomorrow

**Comment by pronobis** [comment] 2015-01-18 18:37
Unfortunately, I rely on SP working well at this point (I'm in the middle of the project now) so I will have to hold off on doing any updates for a couple of days.

**Comment by jasonm23** [comment] 2015-01-19 00:19
Seems it's at the wrong undo point,  

- the first undo reverts to before the paste, 
- the next undo undeletes

this should be one undo step (to be macro consistent.)

![smartparens-paste-undo](https://cloud.githubusercontent.com/assets/71587/5794688/ea8c401e-9fb3-11e4-94ec-9f4067849427.gif)

**Comment by jasonm23** [comment] 2015-01-19 00:29
@Fuco1 sorry, I'm wrong, you're right it's the expected behavior.  (It just Emacs CUA differs from browser text controls, and other editors.)

**Comment by pronobis** [comment] 2015-01-26 05:33
I confirm that everything works now.

**Comment by Fuco1** [comment] 2015-01-27 09:00
@pronobis thanks. I'm fairly confident in the new system now... what is left is to polish the wrapping code rewrite, then fix the tags (they will get merged into pairs), and 1.7 should be ready.

**Comment by pronobis** [comment] 2015-01-27 23:34
Thanks a lot for your work @Fuco1 !

**Closed** 2015-08-13 14:56 UTC
Labels: bug, needs-verification
