### ISSUE TITLE
Spurious quote insertion in latex-mode

### ISSUE THREAD

**Issue by nidrissi** [Fuco1/smartparens#820] opened 2017-11-30 13:20 UTC
## Expected behavior

When the point is before the formula in the following latex document, typing `"` should simply insert a pair of opening and closing quotes:

```
\documentclass{article}
\begin{document}
Insert quotes here:
$f' = 0
\end{document}
```

## Actual behavior

Typing `"` instead insert an opening quote at the point and "closes" the quote after the apostrophe in the formula (but really, it could be an apostrophe followed by a space anywhere in the document, the fact that it's in a formula is irrelevant):

```
\documentclass{article}
\begin{document}
Insert quotes here: ``
$f'' = 0$
\end{document}
```

## Steps to reproduce the problem

Type `"` anywhere in the document before an apostrophe followed by a space (i.e. `' `).

## Environment & version information

- `smartparens` version: 20171126.1241
- Active major-mode: latex-mode
- Emacs version (`M-x emacs-version`): GNU Emacs 25.2.1 (x86_64-w64-mingw32) of 2017-04-24
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: vanilla
- OS: windows-nt

**Comment by nidrissi** [comment] 2017-11-30 13:24
To be honest, after finding out that my documents are littered with `$h'''$` (the inserted text could be several screens below the current one!), I stopped using smartparens in latex-mode until this is fixed...

**Comment by Fuco1** [comment] 2017-11-30 20:39
The problem is that the parser does not know `$` starts a different environment (along with `\[` or `\align` etc).  There is a function `texmathp` in auctex which can detect this but it does not ship with Emacs.  I'm not sure if I want to depend on it just for this one function.  Without this it is quite difficult so I think I will just disable the functionality in latex as a temporary solution.

The issue here is that sometimes smartparens detects that you are "extending" a pair and it also fixes the closing delimiter to keep the balance.  So if you have text 

    foo `|bar' baz

and type the back tick instead of ending with

    foo ``|bar' baz

it will fix the closing quote and the result is syntactically valid

    foo ``|bar'' baz

But for this to make sense both ends of the expression must be in the same environment, which here the dollar sign breaks, but there's no way for emacs's internal state tracker to know that since `$` is not a string delimiter syntax.  It's kind of messy :/

**Comment by Fuco1** [comment] 2017-11-30 21:12
I've fixed this in a somewhat "95%" way... I can't think of many scenarios where this is not going to work.  I will try to come up with some general environment handling setup someday (I would like it for org blocks as well for example)

**Closed** 2017-11-30 21:11 UTC
Labels: bug
