### ISSUE TITLE
single quote in python

### ISSUE THREAD

**Issue by simonpp** [Fuco1/smartparens#575] opened 2016-02-17 20:29 UTC
When I type a single quote in python mode it is not paired, although it should according to `sp-pair-list`. I'm using emacs python-mode, emacs 24.5.1 and smartparens 20160217.1102 from melpa. I'm not sure if the problem is caused by smartparens, since in c++-mode it is working.

**Comment by Wilfred** [comment] 2016-02-17 21:33
Duplicate of #573, you just need to update :)

**Closed by Wilfred** 2016-02-17 21:33 UTC
