### ISSUE TITLE
sp-end-sexp and sp-beginning-sexp unexpected behavior

### ISSUE THREAD

**Issue by richarddwang** [Fuco1/smartparens#859] opened 2018-02-16 08:58 UTC
```
(save-excursion
    ;; If right-char when can't the function will stop
    (if (not (eobp)) (right-char))
    (funcall prev)
    (if (= position (point)) (setq at-beginning t)))
```

When cursor is at anywhere on `save-excursion`

## Expected behavior
Move cursor to the position between `(` and `save-excursion` after `sp-beginning-sexp`
Move cursor to the end like `t))|)` after `sp-end-sexp`

## Actual behavior
Won't move a bit after `sp-end-sexp` or `sp-beggining-sexp`

## Environment & version information
`smartparens` version: 20180204.844
- Active major-mode: lisp-interaction-mode
- Emacs version (`M-x emacs-version`): GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-12-21
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: GNU Emacs
- OS: gnu/linux

**Comment by Fuco1** [comment] 2018-02-16 09:19
I'm assuming you mean `sp-end-of-sexp` and `sp-beginning-of-sexp`.  I've tried but can't reproduce this issue.

Can you try this in an `emacs -q` session (this won't load your config).  You will have to manually load dash and smartparens first because your packages won't initialize either.

**Comment by Fuco1** [comment] 2018-03-04 16:19
Can you please check if this is fixed with the patch fixing #860? I can't reproduce this particular case.

**Comment by frankie8518** [comment] 2018-03-10 09:36
I have leaved a comment on #860 .
"I use smartparens20180308.1042 now, but I still get the same issue.
And I can still use the way specified by issue mentioned in my comment above, to reproduce and to avoid the issue."

**Comment by Fuco1** [comment] 2024-03-24 09:57
There are no functions `sp-end-sexp` or `sp-beggining-sexp`, maybe they come from another package and don't work.  I tried to reproduce the issue with the original buffer posted, calling `sp-end-of-sexp` and `sp-beginning-of-sexp` and they work as intended.

**Closed by Fuco1** 2024-03-24 09:57 UTC
Labels: bug, unconfirmed
