### ISSUE TITLE
additionally defined pairs do not work in the latest version

### ISSUE THREAD

**Issue by xin-jin** [Fuco1/smartparens#416] opened 2015-01-13 21:25 UTC
After updating to the latest version, none of the pairs defined in smartparens-latex (also pairs defined by myself) works (while simple pairs like "()" still work). I degrade it to the 1.4 version in marmalade repo, and things go back to normal.

EDIT: it seems to be a duplication of https://github.com/Fuco1/smartparens/issues/415

**Comment by Fuco1** [comment] 2015-01-14 08:02
Do you mean that they are not inserted or not recognized when you do navigation? For example `\\langle` or `\\big(` insert fine for me.

**Comment by xin-jin** [comment] 2015-01-14 08:15
Ah, sorry, just for the ones I used they didn't work (I actually used my own config rather than smartparens-latex). For instance, $ and \[。Cannot live without these two :(

**Comment by Fuco1** [comment] 2015-01-14 08:22
The pairs where the suffix is a prefix of another pair doesn't work right now (that is the case of `\\[` or `\\\\(`. I will only have time to look at this during the weekend because the fix is going to be non-trivial.

The cause of these bugs is a *major* rewrite of the input handling/pair insertion code---breakage was expected :D

The last tag is a version before these things were merged into the master, so you can use that for the meanwhile.

**Comment by Fuco1** [comment] 2015-01-17 22:04
Please test against the latest master.

**Comment by xin-jin** [comment] 2015-01-17 23:30
Thanks! I think it is working now.

**Closed** 2015-08-13 14:55 UTC
Labels: bug
