### ISSUE TITLE
Strict mode: allows insertion of unmatched closing pair but skips over on backspace

### ISSUE THREAD

**Issue by crowding** [Fuco1/smartparens#688] opened 2016-12-28 22:33 UTC
SP allows insertion of an unmatched closing delimiter:

    "[this (is a | ) test]" -> `]`
    "[this (is a ]| ) test]"

but (when in strict mode) sometimes makes it difficult to delete an unmatched delimiter:

    "[this (is a ]| ) test]" -> DEL
    "[this (is a |] ) test]"

It would be preferable if one of these two didn't happen in strict mode.

**Comment by Fuco1** [comment] 2016-12-29 11:16
Yes, the insertion should be impossible.

**Comment by Fuco1** [comment] 2017-01-04 10:22
This is a duplicate of #421 which was recently fixed, so this problem should be gone.

**Closed by Fuco1** 2017-01-04 10:22 UTC
Labels: enhancement
