### ISSUE TITLE
Default emacs-lisp-mode config + strict-mode unpairs apostrophes when followed by punctuation

### ISSUE THREAD

**Issue by braham-snyder** [Fuco1/smartparens#782] opened 2017-08-11 07:56 UTC
## Expected behavior
With `smartparens-strict-mode`, and `(require 'smartparens-config)`, calling `sp-backward-delete-char` twice from here (with point as `|`) in `emacs-lisp-mode`:

```
;; `a-symbol-name'? I'm|
```
should probably give:
```
;; `a-symbol-name'? I|
```

## Actual behavior

but I instead see

```
;; `a-symbol-name'? I|'
```

Unsurprisingly, this does not occur with only `?`: any of, e.g., `.`, `-`, or `!` suffices (as did every other word and symbol char I tested). 

The above behavior is similar to https://github.com/Fuco1/smartparens/issues/773, but IIUC is unrelated to the stringlike-parser.

## Environment & version information

- `smartparens` version: 20170723.1205
- Active major-mode: `emacs-lisp-mode`
- Emacs version (`M-x emacs-version`): GNU Emacs 25.2.1 (x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G1510)) of 2017-07-25
- Spacemacs/Evil/Other starterkit (specify which)/Vanilla: Vanilla
- OS: OS X El Capitan

Thanks again for `smartparens`!

**Comment by Fuco1** [comment] 2017-08-11 08:27
Oh that's a funny setup :)  I think this is not related to #773 but instead the problem is in the `sp-lisp-invalid-hyperlink-p` method which tries to quess if the hyperlink is valid.  And it does so by using syntax classes.  For some unexplainable reason `?` in E.macs lisp is symbol class so the parser thinks the `'` is inside a symbol and therefore not a valid "hyperlink".

I suppose I will just special-case the `?!.` characters for this check.  And it should probably only behave like punctuation inside comments, because inside code you could, theoretically, name your symbol `foo'bar`.

Gods help us, this syntax class madness is so frustrating :D

**Comment by Fuco1** [comment] 2018-03-04 16:52
Turns out this was the same issue as #786 so it is now fixed along with that.  I will add the above cases to the test suite though to make sure things stay working.

**Closed** 2018-03-04 16:57 UTC
Labels: bug, language:elisp
