### ISSUE TITLE
unable to delete single parens in comments in strict mode

### ISSUE THREAD

**Issue by huahaiy** [Fuco1/smartparens#560] opened 2015-12-30 10:02 UTC
E.g.

;; This is in comment :-)

Deleting the above line still leaves ")" in place

**Comment by Fuco1** [comment] 2015-12-30 10:16
That's by design, parens are also parsed inside comments.

**Comment by Fuco1** [comment] 2016-02-12 20:17
What mode and what command do you do when you delete the line?  I missed your comment about deleting the entire line.  C-k (sp-kill-hybrid-sexp) works for me.

**Comment by Fuco1** [comment] 2017-03-12 12:22
This was fixed in 9ae8d4f

**Closed by Fuco1** 2017-03-12 12:22 UTC
Labels: bug, unconfirmed
