### ISSUE TITLE
Smartparens strict mode backspacing over apostrophized words causes point jump

### ISSUE THREAD

**Issue by dakrone** [Fuco1/smartparens#744] opened 2017-05-02 17:39 UTC
## Expected behavior

Let's assume I'm in the following `org-mode` buffer, `|` is the `point`:

```
* What happens if the ~target_response_rate~ is set too low?

Let's assume we r|
```

And I backspace up to the `'`, all good so far:

```
* What happens if the ~target_response_rate~ is set too low?

Let'|
```

If I hit `backspace` one more time, I expect:

```
* What happens if the ~target_response_rate~ is set too low?

Let|
```

## Actual behavior

Instead, this is what I actually get:

```
* What happens if the ~target_response_rate|~ is set too low?

Let'
```

The cursor jumped up to the last surrounded thing!

## Steps to reproduce the problem

Enable `smartparens-strict-mode`, attempt to duplicate the above buffer in org-mode

## Environment & version information

- `smartparens` version: smartparens-20170430.844
- Active major-mode: org-mode
- Emacs version (`M-x emacs-version`): GNU Emacs 25.2.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.11) of 2017-04-25
- OS: Linux, Fedora 25

**Comment by dakrone** [comment] 2017-05-02 21:16
> I don't use strict mode in org (or other text modes) so I've never noticed.

I use strict mode everywhere and I've noticed this in other modes than just org-mode, would you like reports of where else this bug happens when I come across them?

**Comment by Fuco1** [comment] 2017-05-02 22:59
@dakrone Hm, sure, you can post the additional data here then.  Thanks!

**Comment by dakrone** [comment] 2017-05-03 13:42
Here's another example of `smartparens-strict-mode` misbehaving, this time in `mu4e-message-mode`

Buffer:

```
"Here'|s some text in quotes"
```

Pressing `<backspace>`:

```
"Here's some text in quotes|"
```

Cursor jumps to the end of the text instead of deleting the `'`

**Comment by jethrokuan** [comment] 2017-05-08 16:29
My fix for this is to remove ='= as a pair. This is mostly lifted from @Fuco1 's configuration:

```
(sp-with-modes 'org-mode
         (sp-local-pair "'" nil :actions nil)
         (sp-local-pair "*" "*" :actions '(insert wrap) :unless '(sp-point-after-word-p sp-point-at-bol-p) :wrap "C-*" :skip-match 'sp--org-skip-asterisk)
         (sp-local-pair "_" "_" :unless '(sp-point-after-word-p) :wrap "C-_")
         (sp-local-pair "/" "/" :unless '(sp-point-after-word-p) :post-handlers '(("[d1]" "SPC")))
         (sp-local-pair "~" "~" :unless '(sp-point-after-word-p) :post-handlers '(("[d1]" "SPC")))
         (sp-local-pair "=" "=" :unless '(sp-point-after-word-p) :post-handlers '(("[d1]" "SPC")))
         (sp-local-pair "«" "»"))
```

Also, @Fuco1 the wiki for Pair Management seems to suggest that `:rem` is a valid input for `:actions`, but my emacs lisp interpreter disagrees.

**Comment by Fuco1** [comment] 2017-05-08 21:05
@jethrokuan It should, if it doesn't work for you then please open a new issue with some detail (what form exactly you use etc.).  Thanks!

**Comment by braham-snyder** [comment] 2017-05-09 01:44
I believe this issue is a duplicate of https://github.com/Fuco1/smartparens/issues/709

**Comment by dakrone** [comment] 2017-05-09 02:13
> if it doesn't work for you then please open a new issue with some detail (what form exactly you use etc.). Thanks!

Hmm.. that's too bad about having to remove `'` as a pair though, I do still tend to quote things with `'` and wrap existing things with it. Is there any way this could be solved without removing it as a pair?

**Comment by braham-snyder** [comment] 2017-05-09 02:20
I don't believe he was offering that (removing the `'` pair) as the resolution to the original issue--I think he was only asking for an additional bug report for this potential, tangential issue (which I haven't tested myself) mentioned by @jethrokuan :
> Also, @Fuco1 the wiki for Pair Management seems to suggest that :rem is a valid input for :actions, but my emacs lisp interpreter disagrees.

**Comment by jethrokuan** [comment] 2017-05-09 02:38
That was my solution to using strict-mode in org-mode anyway. There is no good way to determine when it should form a pair, and when it should simply be an apostrophe. An alternative solution is to only wrap when there's a space or word before, although this is probably a contrived solution:

`(sp-pair "'" nil :unless '(sp-point-after-word-p))`

**Comment by braham-snyder** [comment] 2017-05-09 02:48
@jethrokuan I wasn't saying you didn't offer a workaround for the original issue. I was referring to the fact that @Fuco1 still considers the original issue an unresolved bug, and was merely asking for you (@jethrokuan) to file a new, separate issue for this tangential problem you're saying you encountered:
> Also, @Fuco1 the wiki for Pair Management seems to suggest that :rem is a valid input for :actions, but my emacs lisp interpreter disagrees.

> There is no good way to determine when it should form a pair, and when it should simply be an apostrophe. An alternative solution is to only wrap when there's a space or word before, although this is probably a contrived solution:

unless I'm misunderstanding you, you might want to take a look at `sp-navigate-use-textmode-stringlike-parser` (which addresses what I believe you're describing)

**Comment by jethrokuan** [comment] 2017-05-09 06:15
@braham-snyder I understood what you meant, and no offense was taken; I never intended to hijack this issue, just wanted to highlight why I used `:actions nil` instead of `:actions :rem` with my 'solution', which seems different from what the wiki would suggest.

I think I misunderstood the crux of this issue. I think the expected behaviour should be a message in the echo area trying to delete an "unbalanced" pair, rather than the cursor jump.

**Comment by braham-snyder** [comment] 2017-05-09 07:25
@jethrokuan I was just trying to clarify the situation to @dakrone (who, if I understood correctly, misunderstood @Fuco1's message to you about the `:rem` bit as being a reply to his original issue)

> I think I misunderstood the crux of this issue. I think the expected behaviour should be a message in the echo area trying to delete an "unbalanced" pair, rather than the cursor jump.

Actually, I believe @Fuco1 (reasonably) thinks `sp-get-textmode-stringlike-expression` (which see)  can be fixed to  handle this case (`"foo bar" quux'`, etc.) correctly (it already correctly handles, e.g, `foo smartparens' and Emacs'` as using two unpaired apostrophes, not one pair of quotes)

**Comment by Fuco1** [comment] 2017-05-09 08:38
@braham-snyder `sp-navigate-use-textmode-stringlike-parser` should be enabled for all text modes (which `org-mode` is) but the problem here is different.  The strictness checks work rather stupidly by looking if you are at a delimiter and then they do additional work, like find its inner point.  But there is some "skip check" missing which makes SP parser think "hey, this apostrophe really is a pair" but then the real parser which actually looks for a pair skips it because "hey this is just a contraction of `it is`".

The bug here is most likely some forgotten missing check somewhere.

**Comment by dakrone** [comment] 2017-05-09 16:37
> I was just trying to clarify the situation to @dakrone (who, if I understood correctly, misunderstood @Fuco1's message to you about the :rem bit as being a reply to his original issue)

I was only wondering if there was a known technical fix for the bug behavior, it sounds like there isn't yet from Fuco1's last response about a likely forgotten missing check. Thanks for everyone looking into the issue thus far though!

**Closed** 2017-06-18 14:49 UTC
Labels: bug, quotes, specific-mode-support
