### ISSUE TITLE
delayed hook acting up recently

### ISSUE THREAD

**Issue by ilohmar** [Fuco1/smartparens#425] opened 2015-01-22 17:38 UTC
Since a few days, my delayed hook (inserts extra newline and indents, after I use any of several newline-ish commands right after inserting a curly-brace-pair) started acting weirdly:
```lisp
(mapc
 (lambda (c)
   (sp-with-modes '(c-mode csharp-mode cs-mode js-mode awk-mode css-mode)
     (sp-local-pair c nil
                    :post-handlers '(:add (my/create-newline-and-enter-sexp
                                           ;; do this after the following keys/commands
                                           my/newline-and-indent
                                           my/open-line-and-indent
                                           newline
                                           newline-and-indent
                                           open-line
                                           reindent-then-newline-and-indent)))))
 '("(" "{" "["))
```
I insert a pair by pressing "{", I press RET (running my/newline-and-indent) and the hook is *not* run.  When I press RET *again*, the hook *is* finally run.

I am still investigating how this might depend on my configuration.  But what strikes me as odd is the check in `sp--post-command-hook-handler` that is in charge:
```lisp
      ;; Here we run the delayed hooks. See issue #80
      (when (and (not (eq sp-last-operation 'sp-insert-pair))
                 sp-last-inserted-pair)
...
```
After the first RET it fails as `sp-last-operation` is indeed `sp-insert-pair` (ok), and it succeeds the second time, when `sp-last-operation` is `nil` (ok).  It seems that the check expects that sp-last-operation has already been cleared at the time of the first RET, which cannot really have happened (we're only in the post command handler right now).

Can you make any sense of this?  I hope it is not just messed up config on my part.

**Comment by Fuco1** [comment] 2015-01-22 17:48
Yes, thanks for the detailed info.

As of the recent refactoring of the insertion code, some special commands which aren't `self-insert-command` but still trigger it somehow make some SP handlers run twice. I think that is what you're running into as well.

I have some fix locally but haven't pushed it yet because it breaks other things.

If you need a stable version, get the last tagged release.  I will push more update this weekend so you can test the master then (I can't get to it sooner unfortunately).

**Comment by sykora** [comment] 2015-08-20 00:31
Any updates on this? I just spent a bunch of time debugging this issue while trying to set up the standard indent-after-pressing-enter post-handler, and thinking it was an interaction with evil-mode.

**Comment by Fuco1** [comment] 2015-08-20 09:29
Not really, but we're closing in on it :)

What happens when instead of the command name you use event name, such as `"RET"` (or `C-m` or whatever key you use to execute your action).

**Comment by sykora** [comment] 2015-08-20 15:25
For reference, the exact invocation I'm using is: 

    (sp-pair "{" nil :post-handlers '(("||\n[i]" "RET")))

If I actually press my return key, the post-handler is never invoked, no matter how many times I press it. If I press `C-m`, the handler is invoked immediately, which is the desired behaviour.

If I add `"<return>"` to the event list, then the post-handler is invoked after I press my return key the second time. Again for reference, `C-h k` says my return key is `<return>`, and executes `evil-ret-and-indent`. If I replace `"<return>"` with `evil-ret-and-indent` the behaviour is the same, which is also what I'd expect. The handler fires on the second press, but at least it's consistent between `"<return>"` and `evil-ret-and-indent`, the action it's bound to.

I tried instrumenting `sp--post-command-hook-handler`, just in case it's something to do with evil (see your comment on #472), and I found that on pressing the return key for the first time after the pair is inserted (the event on which I expect the post-handler to fire), the value of `sp-last-operation` is `sp-insert-pair`, which is why it's bypassing the handler call. On the subsequent press of `<return>`, `sp-last-operation` is `nil`, thus executing the handler. Pressing `<return>` once more clears `sp-last-inserted-pair` as well.

**Comment by Fuco1** [comment] 2015-08-20 15:35
As I'm always running on master and I don't experience this issue, I strongly suspect it is caused by evil or some other package interfering.  I'm not saying it's a wontfix, because it might as well be our problem, but just to localize it better, could you run your emacs without evil (if it isn't too difficult) and see if the same thing happens?  Ideally without loading it at all because I know evil attaches some hooks to do "magic".

**Comment by Fuco1** [comment] 2016-04-07 19:58
So I've finally started cleaning up the backlog.

I can't reproduce this issue, but what is weirder, I don't understand *at all* how it could work for me, because the code to reset the flag is never executed :D

Any of you guys could test this on your setups and tell me if it works or not?  It would be super appreciated :)  In the meantime I will try to write some tests and get things moving.

**Closed** 2016-05-10 20:13 UTC
Labels: bug
